### ISSUE TITLE
[Bug] Built image versions do not match component versions

### ISSUE THREAD

**Issue by 0xDEC0DE** [temporalio/docker-builds#212]
The official images on Docker Hub have different running versions of the software than what the images advertise.

# Steps to reproduce

```
docker run --rm --entrypoint /usr/local/bin/temporal temporalio/server:1.23.0 --version
docker run --rm --entrypoint /usr/local/bin/temporal temporalio/server:1.24.0 --version
docker run --rm --entrypoint /usr/local/bin/temporal temporalio/server:1.24.0.0 --version
```

# Expected result

```
[...] server 1.23.0 [...]
[...] server 1.24.0 [...]
[...] server 1.24.0 [...]
```
...respectively

# Actual behavior

```
temporal version 0.11.0 (server 1.22.4) (ui 2.21.3)
temporal version 0.0.0-DEV (server 1.23.0) (ui 2.26.2)
temporal version 0.0.0-DEV (server 1.23.0) (ui 2.26.2)
```

# Impact

You do not appear to be shipping the versions you think you are shipping.

**Comment by robholland** [comment]
`temporal` is the command line tool, not the server. The `temporal-server` command will return the versions you expect.
