### ISSUE TITLE
[Feature Request] TLS support for postgreSQL

### ISSUE THREAD

**Issue by NipunaPrashan** [temporalio/docker-builds#59]
### Is your feature request related to a problem? Please describe.
If a PostgreSQL server is enforced SSL connection, temporal-sql-tool should connect with `--tls=true`.

Currently, the connection from temporal to DB is not a SSL connection. Please find the error below when connecting to a SSL enforced database.

```
ERROR   Unable to create SQL database.  {"error": "unable to connect to DB, tried default DB names: postgres,defaultdb, errors: [pq: SSL connection is required. Please specify SSL options and retry. pq: SSL connection is required. Please specify SSL options and retry.]", "logging-call-at": "handler.go:100"}
```

### Describe the solution you'd like

Add `--tls=${SQL_TLS_ENABLED}` for queries in `setup_postgres_schema` method

**Comment by NipunaPrashan** [comment]
@temporal-data @feedmeapples PR is attached.

**Comment by c-thiel** [comment]
I just stumbled over this while deploying Airbyte.
This is related to https://github.com/airbytehq/airbyte/issues/9342

**Comment by AKuzyashin** [comment]
@temporal-data any updates there ?

**Comment by NikoKS** [comment]
somehow, tls is still not working with these env:
```
POSTGRES_TLS_ENABLED="true"
POSTGRES_TLS_DISABLE_HOST_VERIFICATION="true"
```

I need to additionally add the env from here to make it work:
https://github.com/airbytehq/airbyte/issues/26089#issuecomment-1716663378

**Comment by hongbo-miao** [comment]
This is more for future people who come here.

Hi @NikoKS I guess in your case, you are using an old `temporalio/auto-setup` Docker image version. I can confirm Airbyte v0.63.1, Helm Chart v0.199.0 which by default using [temporalio/auto-setup 1.23.0](https://github.com/airbytehq/airbyte-platform/blob/686cdb20a42865cea557871020ecbd44ca8ef8e1/charts/airbyte/values.yaml#L1228)

are picking up these env values https://github.com/temporalio/docker-builds/blob/fdf6808ec70b6263f69b78300620eeb1a4d8bcd0/docker/auto-setup.sh#L38-L43

 😃
