### ISSUE TITLE
[Feature Request] Update admin tools dockerfile to run under non-root user

### ISSUE THREAD

**Issue by tsurdilo** [temporalio/docker-builds#61]
Please update admin tools dockerfile to run under non-root user like it's done with the server dockerfile.

**Comment by mindaugasrukas** [comment]
Could you elaborate on why this is an issue?

**Comment by robholland** [comment]
It's best practise to not run things as root that don't need it. It reduces the risk of vulnerabilities that can be used to escape the container.

**Comment by mindaugasrukas** [comment]
Interesting, I thought that rootless mode was enough.
This is what I found: https://cheatsheetseries.owasp.org/cheatsheets/Docker_Security_Cheat_Sheet.html.

It looks like the recommendation is to run as non-root, no matter if you run as rootless.
